### ISSUE TITLE
Duplicating Messages

### ISSUE THREAD

**Issue by KEKLBruh** [FrozenTear7/twitch-spambot#3] opened 2021-01-03 05:47 UTC
* Connected to irc-ws.chat.twitch.tv:443
* Starting the spambot
[21:41:53, #xqcow, score: 157.99]: OMEGALUL
[21:42:52, #xqcow, score: 73.71]: ??????????
[21:42:52, #xqcow, score: 73.71]: ??????????
[21:42:52, #xqcow, score: 73.71]: ??????????
Received notice: msg_ratelimit
Your message was not sent because you are sending messages too quickly.
Stream ended, stopping the spam

**Comment by FrozenTear7** [comment] 2021-01-03 08:47
I see you're using a version newer than the official release **v1.2** and it's been going through some changes, so please make sure to update it, **v1.3** is coming in a few days, so for now just pull the newest master branch update. The error inside the switch check for notice messages has already been fixed, althought I don't know what's the reason for 4x duplicate of the message.

One explanation would be that yesterday and 2 days ago Twitch was having big issues with their servers and it could have resulted in message error in the script.

If the issue persists after update please notify me again in this issue, preferably with the starting parameters if you're passing any additional ones except from `npm start xqcow`.

**Closed as completed** 2021-01-11 20:41 UTC
Labels: bug
